name: CI Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: install required packages
        run: sudo apt update && sudo apt-get install pkgconf libglew-dev libopenal-dev libglfw3-dev libfreetype-dev
      - uses: actions/checkout@v2
      - name: build
        run: cd ext/minitscript/ && make mains && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib && ./bin/minitscript/tools/minitscript --working-directory=../.. ../../make.tscript --arguments clean libraries executables && cd ../..
